package com.github.dwursteisen.minigdx.input

import android.view.KeyEvent

val Key.keyCode: Int
    get() {
        return when (this) {
            Key.ANY_KEY -> KeyEvent.KEYCODE_UNKNOWN
            Key.BACKSPACE -> KeyEvent.KEYCODE_BACK
            Key.TAB -> KeyEvent.KEYCODE_TAB
            Key.ENTER -> KeyEvent.KEYCODE_ENTER
            Key.SHIFT -> KeyEvent.KEYCODE_SHIFT_LEFT
            Key.CTRL -> KeyEvent.KEYCODE_CTRL_LEFT
            Key.ALT -> KeyEvent.KEYCODE_ALT_LEFT
            Key.PAUSE_BREAK -> KeyEvent.KEYCODE_BREAK
            Key.CAPS_LOCK -> KeyEvent.KEYCODE_CAPS_LOCK
            Key.ESCAPE -> KeyEvent.KEYCODE_ESCAPE
            Key.PAGE_UP -> KeyEvent.KEYCODE_PAGE_UP
            Key.SPACE -> KeyEvent.KEYCODE_SPACE
            Key.PAGE_DOWN -> KeyEvent.KEYCODE_PAGE_DOWN
            Key.END -> KeyEvent.KEYCODE_MOVE_END
            Key.HOME -> KeyEvent.KEYCODE_MOVE_HOME
            Key.ARROW_LEFT -> KeyEvent.KEYCODE_DPAD_LEFT
            Key.ARROW_UP -> KeyEvent.KEYCODE_DPAD_UP
            Key.ARROW_RIGHT -> KeyEvent.KEYCODE_DPAD_RIGHT
            Key.ARROW_DOWN -> KeyEvent.KEYCODE_DPAD_DOWN
            Key.PRINT_SCREEN -> KeyEvent.KEYCODE_UNKNOWN
            Key.INSERT -> KeyEvent.KEYCODE_INSERT
            Key.DELETE -> KeyEvent.KEYCODE_DEL
            Key.NUM0 -> KeyEvent.KEYCODE_NUMPAD_0
            Key.NUM1 -> KeyEvent.KEYCODE_NUMPAD_1
            Key.NUM2 -> KeyEvent.KEYCODE_NUMPAD_2
            Key.NUM3 -> KeyEvent.KEYCODE_NUMPAD_3
            Key.NUM4 -> KeyEvent.KEYCODE_NUMPAD_4
            Key.NUM5 -> KeyEvent.KEYCODE_NUMPAD_5
            Key.NUM6 -> KeyEvent.KEYCODE_NUMPAD_6
            Key.NUM7 -> KeyEvent.KEYCODE_NUMPAD_7
            Key.NUM8 -> KeyEvent.KEYCODE_NUMPAD_8
            Key.NUM9 -> KeyEvent.KEYCODE_NUMPAD_9
            Key.A -> KeyEvent.KEYCODE_A
            Key.B -> KeyEvent.KEYCODE_B
            Key.C -> KeyEvent.KEYCODE_C
            Key.D -> KeyEvent.KEYCODE_D
            Key.E -> KeyEvent.KEYCODE_E
            Key.F -> KeyEvent.KEYCODE_F
            Key.G -> KeyEvent.KEYCODE_G
            Key.H -> KeyEvent.KEYCODE_H
            Key.I -> KeyEvent.KEYCODE_I
            Key.J -> KeyEvent.KEYCODE_J
            Key.K -> KeyEvent.KEYCODE_K
            Key.L -> KeyEvent.KEYCODE_L
            Key.M -> KeyEvent.KEYCODE_M
            Key.N -> KeyEvent.KEYCODE_N
            Key.O -> KeyEvent.KEYCODE_O
            Key.P -> KeyEvent.KEYCODE_P
            Key.Q -> KeyEvent.KEYCODE_Q
            Key.R -> KeyEvent.KEYCODE_R
            Key.S -> KeyEvent.KEYCODE_S
            Key.T -> KeyEvent.KEYCODE_T
            Key.U -> KeyEvent.KEYCODE_U
            Key.V -> KeyEvent.KEYCODE_V
            Key.W -> KeyEvent.KEYCODE_W
            Key.X -> KeyEvent.KEYCODE_X
            Key.Y -> KeyEvent.KEYCODE_Y
            Key.Z -> KeyEvent.KEYCODE_Z
            Key.LEFT_WINDOW_KEY -> KeyEvent.KEYCODE_WINDOW
            Key.RIGHT_WINDOW_KEY -> KeyEvent.KEYCODE_WINDOW
            Key.SELECT_KEY -> KeyEvent.KEYCODE_BUTTON_SELECT
            Key.NUMPAD0 -> KeyEvent.KEYCODE_NUMPAD_0
            Key.NUMPAD1 -> KeyEvent.KEYCODE_NUMPAD_1
            Key.NUMPAD2 -> KeyEvent.KEYCODE_NUMPAD_2
            Key.NUMPAD3 -> KeyEvent.KEYCODE_NUMPAD_3
            Key.NUMPAD4 -> KeyEvent.KEYCODE_NUMPAD_4
            Key.NUMPAD5 -> KeyEvent.KEYCODE_NUMPAD_5
            Key.NUMPAD6 -> KeyEvent.KEYCODE_NUMPAD_6
            Key.NUMPAD7 -> KeyEvent.KEYCODE_NUMPAD_7
            Key.NUMPAD8 -> KeyEvent.KEYCODE_NUMPAD_8
            Key.NUMPAD9 -> KeyEvent.KEYCODE_NUMPAD_9
            Key.MULTIPLY -> KeyEvent.KEYCODE_NUMPAD_MULTIPLY
            Key.ADD -> KeyEvent.KEYCODE_NUMPAD_ADD
            Key.SUBTRACT -> KeyEvent.KEYCODE_NUMPAD_SUBTRACT
            Key.DECIMAL_POINT -> KeyEvent.KEYCODE_NUMPAD_COMMA
            Key.DIVIDE -> KeyEvent.KEYCODE_NUMPAD_DIVIDE
            Key.F1 -> KeyEvent.KEYCODE_F1
            Key.F2 -> KeyEvent.KEYCODE_F2
            Key.F3 -> KeyEvent.KEYCODE_F3
            Key.F4 -> KeyEvent.KEYCODE_F4
            Key.F5 -> KeyEvent.KEYCODE_F5
            Key.F6 -> KeyEvent.KEYCODE_F6
            Key.F7 -> KeyEvent.KEYCODE_F7
            Key.F8 -> KeyEvent.KEYCODE_F8
            Key.F9 -> KeyEvent.KEYCODE_F9
            Key.F10 -> KeyEvent.KEYCODE_F10
            Key.F11 -> KeyEvent.KEYCODE_F11
            Key.F12 -> KeyEvent.KEYCODE_F12
            Key.NUM_LOCK -> KeyEvent.KEYCODE_NUM_LOCK
            Key.SCROLL_LOCK -> KeyEvent.KEYCODE_SCROLL_LOCK
            Key.MY_COMPUTER -> KeyEvent.KEYCODE_UNKNOWN
            Key.MY_CALCULATOR -> KeyEvent.KEYCODE_UNKNOWN
            Key.SEMI_COLON -> KeyEvent.KEYCODE_SEMICOLON
            Key.EQUAL_SIGN -> KeyEvent.KEYCODE_EQUALS
            Key.COMMA -> KeyEvent.KEYCODE_COMMA
            Key.DASH -> KeyEvent.KEYCODE_MINUS
            Key.PERIOD -> KeyEvent.KEYCODE_PERIOD
            Key.FORWARD_SLASH -> KeyEvent.KEYCODE_SLASH
            Key.OPEN_BRACKET -> KeyEvent.KEYCODE_LEFT_BRACKET
            Key.BACK_SLASH -> KeyEvent.KEYCODE_BACKSLASH
            Key.CLOSE_BRAKET -> KeyEvent.KEYCODE_RIGHT_BRACKET
            Key.SINGLE_QUOTE -> KeyEvent.KEYCODE_SEMICOLON
            Key.DPAD_CENTER -> KeyEvent.KEYCODE_DPAD_CENTER
        }
    }
